image: node:20

variables:
  NODE_OPTIONS: "--openssl-legacy-provider"
  FORCE_COLOR: "1"

before_script:
  - apt-get update -qq
  - apt-get upgrade -qqy
  - apt-get install -yqq vim links lynx git diffutils htop curl wget p7zip-full unzip zip sed gcc g++ make libfreetype6-dev libaio1 libaio-dev libonig-dev libpng-dev
  - npm install
  - npx playwright install --with-deps chromium

stages:
  - build
  - test

webship-js-build:
  stage: build
  script:
    - npm start &
    - npm test

  only:
    refs:
      - tags
      - branches
