image: node:20

pipelines:
  default:
    - step:
        name: Install and Test
        caches:
          - node
        script:
          - npm install
          - npx playwright install --with-deps chromium
          - npm start &
          - sleep 3
          - FORCE_COLOR=1 npm test
