image: node:20

pipelines:
  default:
    - step:
        name: Install and Test
        services:
          - selenium
        caches:
          - node
        script:
          - npm install
          - npm test

definitions:
  services:
    selenium:
      image: selenium/standalone-chrome:latest
      ports:
        - 4444:4444
