version: 2.1
defaults: &defaults
  docker:
    - image: cimg/base:stable-20.04
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
  environment:
    FORCE_COLOR: "1"
commands:
  webship-js-build:
    steps:
      - checkout
      ## Useful must have utils.
      - run:
          name: Useful must have utils
          command: |
            sudo apt -qq update
            sudo apt -qqy upgrade
            sudo apt -yqq install vim links lynx git diffutils htop curl wget p7zip-full unzip zip sed gcc g++ make libfreetype6-dev libaio1 libaio-dev libonig-dev libpng-dev

      ## Install node js, npm
      - run:
          name: Install node js
          command: |
            curl -sL https://deb.nodesource.com/setup_20.x | sudo bash -
            sudo apt install -y nodejs

jobs:
  webship-js-testing:
    <<: *defaults
    steps:
      - webship-js-build
      ## Install npm dependencies
      - run:
          name: Install npm dependencies
          command: |
            npm install
      ## Install Playwright browsers
      - run:
          name: Install Playwright browsers
          command: |
            npx playwright install --with-deps chromium
      - run:
          name: Start virtual server
          command: |
            export NODE_OPTIONS=--openssl-legacy-provider
            npm start
          background: true
      - run:
          name: Test
          command: |
            npm test
workflows:
  version: 2
  webship-js-workflow:
    jobs:
      - webship-js-testing:
          filters:
            tags:
              only: /^1.0.*/
            branches:
              only: /^1.0.x/
