name: Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TEST_BASE_URL: http://localhost:8080
      FORCE_COLOR: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Start virtual server
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm start &

      - name: Run tests
        run: npm test
